name: spendly
description: ""
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  auto_route: ^10.1.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^8.3.0
  google_fonts: ^6.3.0
  hydrated_bloc: ^10.1.1
  icons_plus: ^5.0.0
  injectable: ^2.5.1
  path_provider: ^2.1.5

dev_dependencies:
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
